### PR TITLE
changed structure to make installation via composer possible

### PR DESCRIPTION
**Pull request by dwirt**
this eliminates the need to copy the files directly into the magento directory and instead can be installed directly via composer like any other module

### CODE REVIEW

**Comment by Bugfighter** [comment]
thanks for the pull request!
we will take a deeper look to the change next week

**Comment by dwirt** [comment]
I've seen some Pull Requests already getting merged. Can you please take a look at this? It just moves the files from `app/code/RatePAY/Payment` to the root of the repository. I's a simple change, but allows you to install the module via composer like other magento 2 modules.

**Comment by AnnegretS** [comment]
Hey dwirt thanks for the pull request, we will check this today :)

**Comment by FatchipRobert** [comment]
Hey @dwirt, I just relocated the code to match the common Magento2 module github layout, the same as you did.
Just did it an an own pull-request to keep all the recent changes in the module without merging or editing conflicts.

**Pull request closed without merging**
